# Generated by Django 5.0.4 on 2024-05-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('verified_user', 'Can read all books')]},
        ),
    ]
